// Do not edit. This file is machine generated by the Resource DLL Wizard.

library KeyType;

{ITE} {DFMFileType} {AuthenticationForm.dfm}
{ITE} {DFMFileType} {CustomTextFrame.dfm}
{ITE} {DFMFileType} {DataModule.dfm}
{ITE} {DFMFileType} {ExternalSourcesFrame.dfm}
{ITE} {DFMFileType} {GeneratedTextFrame.dfm}
{ITE} {DFMFileType} {LoginFrame.dfm}
{ITE} {DFMFileType} {MainForm.dfm}
{ITE} {DFMFileType} {MainFrame.dfm}
{ITE} {DFMFileType} {OptionsFrame.dfm}
{ITE} {DFMFileType} {PracticeForm.dfm}
{ITE} {DFMFileType} {PracticeFrame.dfm}
{ITE} {DFMFileType} {PreferencesForm.dfm}
{ITE} {DFMFileType} {RegisterFrame.dfm}
{ITE} {RCFileType} {Win32\Debug\KeyType_DRC.rc}

{$R 'AuthenticationForm.dfm' 'FAuthentication:TForm'}
{$R 'CustomTextFrame.dfm' 'FrCustomText:TForm'}
{$R 'DataModule.dfm' 'DataModule1:TForm'}
{$R 'ExternalSourcesFrame.dfm' 'FrExternalSources:TForm'}
{$R 'GeneratedTextFrame.dfm' 'FrGeneratedText:TForm'}
{$R 'LoginFrame.dfm' 'FrLogin:TForm'}
{$R 'MainForm.dfm' 'FMain:TForm'}
{$R 'MainFrame.dfm' 'FrMain:TForm'}
{$R 'OptionsFrame.dfm' 'FrOptions:TForm'}
{$R 'PracticeForm.dfm' 'FPractice:TForm'}
{$R 'PracticeFrame.dfm' 'FrPractice:TForm'}
{$R 'PreferencesForm.dfm' 'FPreferences:TForm'}
{$R 'RegisterFrame.dfm' 'FrRegister:TForm'}
{$R 'Win32\Debug\KeyType_DRC.res' 'Win32\Debug\KeyType_DRC.rc'}

{$E HRV}

begin
end.
