// Do not edit. This file is machine generated by the Resource DLL Wizard.

library KeyType;

{ITE} {DFMFileType} {Core\dal\DataModule.dfm}
{ITE} {DFMFileType} {core\forms\authentication\AuthenticationForm.dfm}
{ITE} {DFMFileType} {core\forms\authentication\LoginFrame.dfm}
{ITE} {DFMFileType} {core\forms\authentication\RegisterFrame.dfm}
{ITE} {DFMFileType} {core\forms\converter\ConverterForm.dfm}
{ITE} {DFMFileType} {core\forms\lessons\CoursesFrame.dfm}
{ITE} {DFMFileType} {core\forms\lessons\LessonResultsForm.dfm}
{ITE} {DFMFileType} {Core\forms\lessons\LessonsForm.dfm}
{ITE} {DFMFileType} {core\forms\lessons\LessonsFrame.dfm}
{ITE} {DFMFileType} {core\forms\logs\LogsForm.dfm}
{ITE} {DFMFileType} {core\forms\main\FlyingWordsFrame.dfm}
{ITE} {DFMFileType} {core\forms\main\FlyingWordsStatsFrame.dfm}
{ITE} {DFMFileType} {core\forms\main\Lessons2Frame.dfm}
{ITE} {DFMFileType} {core\forms\main\MainForm.dfm}
{ITE} {DFMFileType} {core\forms\main\MainFrame.dfm}
{ITE} {DFMFileType} {core\forms\main\PracticeFrame.dfm}
{ITE} {DFMFileType} {core\forms\main\TypingStatsFrame.dfm}
{ITE} {DFMFileType} {core\forms\main\TypingTextFrame.dfm}
{ITE} {DFMFileType} {core\forms\practice\CustomTextFrame.dfm}
{ITE} {DFMFileType} {core\forms\practice\ExternalSourcesFrame.dfm}
{ITE} {DFMFileType} {core\forms\practice\GeneratedTextFrame.dfm}
{ITE} {DFMFileType} {core\forms\practice\KeyboardFrame.dfm}
{ITE} {DFMFileType} {core\forms\practice\OptionsFrame.dfm}
{ITE} {DFMFileType} {Core\forms\practice\PracticeForm.dfm}
{ITE} {DFMFileType} {core\forms\practice\PracticeSourceForm.dfm}
{ITE} {DFMFileType} {core\forms\preferences\PreferencesForm.dfm}
{ITE} {DFMFileType} {core\forms\profile\AchievementsForm.dfm}
{ITE} {DFMFileType} {core\forms\profile\ProfileForm.dfm}
{ITE} {RCFileType} {Win32\Debug\KeyType_DRC.rc}

{$R 'Core\dal\DataModule.dfm' 'DataModule1:TForm'}
{$R 'core\forms\authentication\AuthenticationForm.dfm' 'FAuthentication:TForm'}
{$R 'core\forms\authentication\LoginFrame.dfm' 'FrLogin:TForm'}
{$R 'core\forms\authentication\RegisterFrame.dfm' 'FrRegister:TForm'}
{$R 'core\forms\converter\ConverterForm.dfm' 'FConverter:TForm'}
{$R 'core\forms\lessons\CoursesFrame.dfm' 'FrCourses:TForm'}
{$R 'core\forms\lessons\LessonResultsForm.dfm' 'FLessonResults:TForm'}
{$R 'Core\forms\lessons\LessonsForm.dfm' 'FLessons:TForm'}
{$R 'core\forms\lessons\LessonsFrame.dfm' 'FrLessons:TForm'}
{$R 'core\forms\logs\LogsForm.dfm' 'FLogs:TForm'}
{$R 'core\forms\main\FlyingWordsFrame.dfm' 'FrFlyingWords:TForm'}
{$R 'core\forms\main\FlyingWordsStatsFrame.dfm' 'FrFlyingWordsStats:TForm'}
{$R 'core\forms\main\Lessons2Frame.dfm' 'FrLessons2:TForm'}
{$R 'core\forms\main\MainForm.dfm' 'FMain:TForm'}
{$R 'core\forms\main\MainFrame.dfm' 'FrMain:TForm'}
{$R 'core\forms\main\PracticeFrame.dfm' 'FrPractice:TForm'}
{$R 'core\forms\main\TypingStatsFrame.dfm' 'FrTypingStats:TForm'}
{$R 'core\forms\main\TypingTextFrame.dfm' 'FrTypingText:TForm'}
{$R 'core\forms\practice\CustomTextFrame.dfm' 'FrCustomText:TForm'}
{$R 'core\forms\practice\ExternalSourcesFrame.dfm' 'FrExternalSources:TForm'}
{$R 'core\forms\practice\GeneratedTextFrame.dfm' 'FrGeneratedText:TForm'}
{$R 'core\forms\practice\KeyboardFrame.dfm' 'FrKeyboard:TForm'}
{$R 'core\forms\practice\OptionsFrame.dfm' 'FrOptions:TForm'}
{$R 'Core\forms\practice\PracticeForm.dfm' 'FPractice:TForm'}
{$R 'core\forms\practice\PracticeSourceForm.dfm' 'FPracticeSource:TForm'}
{$R 'core\forms\preferences\PreferencesForm.dfm' 'FPreferences:TForm'}
{$R 'core\forms\profile\AchievementsForm.dfm' 'FAchievements:TForm'}
{$R 'core\forms\profile\ProfileForm.dfm' 'FProfile:TForm'}
{$R 'Win32\Debug\KeyType_DRC.res' 'Win32\Debug\KeyType_DRC.rc'}

{$E HRV}

begin
end.
